/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/commerce/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read config using a server app token.
         * @description Returns site metadata, GTM config, checkout copy, and browser-safe payment provider config. The site is inferred from the server app token.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Commerce config. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommerceConfigResponse"];
                    };
                };
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commerce/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active products using a server app token.
         * @description Lists active storefront-facing products for the token-bound site. Only active variants are returned.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                    q?: string;
                    tag?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active product list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSuccess"] & {
                            data?: components["schemas"]["Product"][];
                        };
                    };
                };
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commerce/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one active product using a server app token.
         * @description Reads one active product by slug for the token-bound site.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Product detail. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSuccess"] & {
                            data?: components["schemas"]["Product"];
                        };
                    };
                };
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commerce/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read content blocks using a server app token.
         * @description Reads blocks for the token-bound site. Use either `keys` for batch lookup by key, or `type` with optional pagination for list-by-type.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Comma-separated block keys. Up to 50 keys. */
                    keys?: string;
                    type?: string;
                    page?: number;
                    perPage?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Block lookup result. `keys` returns BlocksByKey; `type` returns BlocksList. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": (components["schemas"]["ApiSuccess"] & {
                            data?: components["schemas"]["BlocksByKey"];
                        }) | (components["schemas"]["ApiSuccess"] & {
                            data?: components["schemas"]["BlocksList"];
                        });
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commerce/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an order using a server app token.
         * @description Creates an order for the token-bound site. Use this from SSR storefront server routes, not browser code.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrderRequest"];
                };
            };
            responses: {
                /** @description Created order. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSuccess"] & {
                            data?: components["schemas"]["Order"];
                        };
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commerce/orders/{orderNo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read an order using a server app token.
         * @description Reads an order for the token-bound site.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Order detail. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSuccess"] & {
                            data?: components["schemas"]["Order"];
                        };
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commerce/payments/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a provider payment using a server app token.
         * @description Creates or reuses a PayPal order or Stripe PaymentIntent for the token-bound site.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePaymentRequest"];
                };
            };
            responses: {
                /** @description Provider payment data for the browser payment SDK. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSuccess"] & {
                            data?: components["schemas"]["CreatePaymentResult"];
                        };
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commerce/payments/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Capture and verify payment using a server app token.
         * @description Verifies the provider payment server-side. Returns the updated order when paid.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CapturePaymentRequest"];
                };
            };
            responses: {
                /** @description Updated order after capture verification. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiSuccess"] & {
                            data?: components["schemas"]["Order"];
                        };
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiSuccess: {
            /** @constant */
            success: true;
            data: unknown;
        };
        /**
         * @example {
         *       "success": false,
         *       "data": "Unauthorized"
         *     }
         */
        ApiError: {
            /** @constant */
            success: false;
            data: string | {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        Currency: "USD" | "CNY" | "EUR" | "GBP" | "JPY" | "HKD" | "AUD" | "CAD" | "SGD";
        ProductSeo: {
            title?: string;
            description?: string;
            keywords?: string[];
            image?: string;
            canonicalPath?: string;
            noindex?: boolean;
        };
        ProductReview: {
            author?: string;
            avatar?: string;
            rating?: number;
            title?: string;
            content: string;
            date?: string;
            purchased?: string;
            helpfulCount?: number;
            images?: string[];
            sourceReviewId?: string;
        };
        ProductMeta: {
            source?: string;
            sourceProductId?: string;
            sourceProductUrl?: string;
            seo?: components["schemas"]["ProductSeo"];
            video?: string;
            sellingPoints?: string[];
            attributes?: {
                [key: string]: string;
            };
            decoration?: {
                [key: string]: unknown;
            };
            reviews?: components["schemas"]["ProductReview"][];
        } & {
            [key: string]: unknown;
        };
        ProductVariant: {
            id: string;
            productId: string;
            site: string;
            sku: string;
            optionValues: {
                [key: string]: string;
            };
            decoration: {
                [key: string]: unknown;
            };
            /** @description Minor currency unit, for example cents for USD. */
            price: number;
            compareAtPrice?: number | null;
            stock: number;
            image?: string | null;
            /** @enum {string} */
            status: "active" | "inactive" | "archived";
            createdAt: string;
            updatedAt: string;
        };
        Product: {
            id: string;
            site: string;
            title: string;
            slug: string;
            /** @enum {string} */
            status: "active";
            currency: components["schemas"]["Currency"];
            tags: string[];
            galleryImages: string[];
            mainImage: string | null;
            meta: components["schemas"]["ProductMeta"];
            content: string | null;
            createdAt: string;
            updatedAt: string;
            variants: components["schemas"]["ProductVariant"][];
            minPrice: number;
            maxPrice: number;
            totalStock: number;
        };
        SiteMetadata: {
            name: string;
            legalName: string;
            domain: string;
            logoUrl: string;
            logoAlt: string;
            supportEmail: string;
            privacyEmail: string;
            supportResponseTime: string;
            policyUpdatedAt: string;
            copyrightYear: string;
            cdnBaseUrl: string;
        };
        CommerceConfig: {
            site: components["schemas"]["SiteMetadata"];
            google: {
                gtmId: string;
            };
            checkout: {
                successNotice: string;
            };
            payments: {
                paypal: {
                    enabled: boolean;
                    creditCardEnabled: boolean;
                    /** @enum {string} */
                    mode: "sandbox" | "live";
                    clientId: string;
                };
                stripe: {
                    enabled: boolean;
                    /** @enum {string} */
                    mode: "sandbox" | "live";
                    publishableKey: string;
                };
            };
        };
        CommerceConfigResponse: components["schemas"]["ApiSuccess"] & {
            data?: components["schemas"]["CommerceConfig"];
        };
        Block: {
            key: string;
            type: string;
            meta: {
                [key: string]: unknown;
            };
            content: string;
            updatedAt: string;
        };
        BlocksByKey: {
            [key: string]: components["schemas"]["Block"];
        };
        BlocksList: {
            items: components["schemas"]["Block"][];
            total: number;
        };
        OrderCustomer: {
            /** Format: email */
            email: string;
            /** @default  */
            phone: string;
            firstName: string;
            lastName: string;
        };
        OrderAddress: {
            address1: string;
            /** @default  */
            address2: string;
            city: string;
            state: string;
            postalCode: string;
            /** @example US */
            country: string;
        };
        OrderItemInput: {
            productSlug: string;
            sku: string;
            quantity: number;
        };
        CreateOrderRequest: {
            customer: components["schemas"]["OrderCustomer"];
            billingAddress?: components["schemas"]["OrderAddress"];
            /** @default true */
            billingAddressAsShippingAddress: boolean;
            shippingAddress?: components["schemas"]["OrderAddress"];
            items: components["schemas"]["OrderItemInput"][];
        };
        OrderItem: {
            id: string;
            orderId: string;
            site: string;
            productId: string;
            variantId: string;
            productSlug: string;
            productTitle: string;
            sku: string;
            optionValues: {
                [key: string]: string;
            };
            image: string | null;
            quantity: number;
            unitPrice: number;
            lineTotal: number;
            createdAt: string;
        };
        OrderPayment: {
            id: string;
            site: string;
            orderId: string;
            /** @enum {string} */
            provider: "paypal" | "stripe";
            fundingSource: string | null;
            providerOrderId: string | null;
            providerCaptureId: string | null;
            providerPayerId: string | null;
            /** @enum {string} */
            status: "created" | "approved" | "captured" | "failed" | "refunded";
            amount: number;
            currency: components["schemas"]["Currency"];
            createdAt: string;
            updatedAt: string;
        };
        Order: {
            id: string;
            site: string;
            orderNo: string;
            /** @enum {string} */
            status: "pending" | "processing" | "done" | "cancelled";
            /** @enum {string} */
            paymentStatus: "unpaid" | "pending" | "paid" | "failed" | "refunded";
            currency: components["schemas"]["Currency"];
            subtotalAmount: number;
            shippingAmount: number;
            taxAmount: number;
            totalAmount: number;
            itemCount: number;
            customer: components["schemas"]["OrderCustomer"];
            billingAddress: components["schemas"]["OrderAddress"];
            shippingAddress: components["schemas"]["OrderAddress"];
            items: components["schemas"]["OrderItem"][];
            payments: components["schemas"]["OrderPayment"][];
            createdAt: string;
            updatedAt: string;
        };
        CreatePaymentRequest: {
            orderNo: string;
            /** @enum {string} */
            provider: "paypal" | "stripe";
            /** @description PayPal only. Use `card` for PayPal Card Fields or `paypal` for wallet checkout. */
            fundingSource?: string;
        };
        CreatePaymentResult: {
            orderNo: string;
            /** @enum {string} */
            provider: "paypal" | "stripe";
            fundingSource?: string | null;
            providerOrderId: string;
            /** @description Stripe only. Use with Stripe.js Payment Element. */
            clientSecret?: string;
            currency: components["schemas"]["Currency"];
            totalAmount: number;
            items: components["schemas"]["OrderItem"][];
        };
        CapturePaymentRequest: {
            orderNo: string;
            /** @enum {string} */
            provider: "paypal" | "stripe";
            providerOrderId: string;
        };
    };
    responses: {
        /** @description Error response. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
